In [3]:
!ls

'FRED Data.ipynb'

In [28]:
from fredapi import Fred
import pandas as pd

In [5]:
API_KEY = open("../FED-api-key","r").readlines()[0].strip()
API_KEY

'271eb89dc91f9bfb7da8f33ef622a933'

In [6]:
fred = Fred(api_key=API_KEY)
data = fred.get_series('SP500')
data

2010-01-01        NaN
2010-01-04    1132.99
2010-01-05    1136.52
2010-01-06    1137.14
2010-01-07    1141.69
               ...
2019-12-25        NaN
2019-12-26    3239.91
2019-12-27    3240.02
2019-12-30    3221.29
2019-12-31    3230.78
Length: 2608, dtype: float64

In [21]:
MAX_SERIES = 154

In [36]:
df = fred.search_by_category(1)
for i in range(2,MAX_SERIES+1):
    try:
        df_ = fred.search_by_category(i)
        df = pd.concat([df, df_])
        print(df.shape)
    except ValueError:
        print("No series ", i)
        continue

No series  2
(3038, 15)
(3455, 15)
(3496, 15)
(3884, 15)
No series  7
No series  8
(3991, 15)
(3993, 15)
No series  11
(4034, 15)
No series  13
No series  14
No series  15
(4183, 15)
(4348, 15)
No series  18
No series  19
No series  20
(5708, 15)
No series  22
No series  23
No series  24
(5776, 15)
(5792, 15)
No series  27
(5825, 15)
(5875, 15)
(5885, 15)
(5900, 15)
No series  32
No series  33
No series  34
No series  35
No series  36
No series  37
No series  38
No series  39
No series  40
No series  41
No series  42
No series  43
No series  44
No series  45
No series  46
No series  47
No series  48
No series  49
No series  50
(5905, 15)
No series  52
No series  53
No series  54
No series  55
No series  56
No series  57
No series  58
No series  59
No series  60
No series  61
No series  62
No series  63
No series  64
(5919, 15)
(5933, 15)
(5947, 15)
(5961, 15)
(5975, 15)
(5989, 15)
(6003, 15)
(6010, 15)
No series  73
No series  74
No series  75
No series  76
No series  77
No series  78
No series  79
No series  80
No series  81
(6175, 15)
No series  83
(6193, 15)
(6211, 15)
(6229, 15)
(6247, 15)
(6265, 15)
(6283, 15)
(6301, 15)
(6319, 15)
(6337, 15)
(6442, 15)
(6477, 15)
(6516, 15)
(6523, 15)
(6573, 15)
No series  98
(6716, 15)
(6859, 15)
(6974, 15)
No series  102
No series  103
(7032, 15)
(7111, 15)
(7471, 15)
(8600, 15)
(8704, 15)
(8830, 15)
(9016, 15)
No series  111
(9341, 15)
No series  113
(9355, 15)
(9403, 15)
No series  116
No series  117
No series  118
No series  119
(9452, 15)
(9493, 15)
(9511, 15)
(9572, 15)
(9599, 15)
(9646, 15)
No series  126
(9857, 15)
No series  128
No series  129
No series  130
No series  131
No series  132
(10093, 15)
No series  134
No series  135
No series  136
No series  137
No series  138
No series  139
No series  140
No series  141
No series  142
No series  143
No series  144
No series  145
No series  146
No series  147
No series  148
(11424, 15)
(13269, 15)
(14919, 15)
(16399, 15)
(17820, 15)
(19389, 15)

In [40]:
df_monthly = df[df["frequency"]=="Monthly"]
print(df_monthly.shape)
df_monthly.head()

(4293, 15)

,id,realtime_start,realtime_end,title,observation_start,observation_end,frequency,frequency_short,units,units_short,seasonal_adjustment,seasonal_adjustment_short,last_updated,popularity,notes
series id,,,,,,,,,,,,,,,
ISRATIO,ISRATIO,2020-01-02,2020-01-02,Total Business: Inventories to Sales Ratio,1992-01-01,2019-10-01,Monthly,M,Ratio,Ratio,Seasonally Adjusted,SA,2019-12-13 09:11:02-06:00,61,"Effective June 14, 2001, data were reconstruct..."
TOTBUSIMNSA,TOTBUSIMNSA,2020-01-02,2020-01-02,Total Business Inventories,1992-01-01,2019-10-01,Monthly,M,Millions of Dollars,Mil. of $,Not Seasonally Adjusted,NSA,2019-12-13 09:11:06-06:00,8,None
TOTBUSIRNSA,TOTBUSIRNSA,2020-01-02,2020-01-02,Total Business: Inventories to Sales Ratio,1992-01-01,2019-10-01,Monthly,M,Ratio,Ratio,Not Seasonally Adjusted,NSA,2019-12-13 09:11:04-06:00,19,The inventories to sales ratios show the relat...
TOTBUSMPCIMNSA,TOTBUSMPCIMNSA,2020-01-02,2020-01-02,Total Business Inventories,1992-02-01,2019-10-01,Monthly,M,Percent Change,% Chg.,Not Seasonally Adjusted,NSA,2019-12-13 09:11:07-06:00,4,None
TOTBUSMPCIMSA,TOTBUSMPCIMSA,2020-01-02,2020-01-02,Total Business Inventories,1992-02-01,2019-10-01,Monthly,M,Percent Change,% Chg.,Seasonally Adjusted,SA,2019-12-13 09:11:05-06:00,17,None

In [44]:
df_monthly_nsa = df_monthly[df_monthly["seasonal_adjustment_short"]=="NSA"]
print(df_monthly_nsa.shape)

(2081, 15)

In [93]:
s = list(df_monthly["id"])[0]
print(s)
s_df = fred.get_series_first_release(s)
s_df = s_df.reset_index()
s_df.columns = ["date",s]
s_df.head()

ISRATIO

        date ISRATIO
0 1948-01-01    1.38
1 1948-02-01    1.41
2 1948-03-01    1.42
3 1948-04-01    1.41
4 1948-05-01    1.42

In [109]:
s = list(df_monthly_nsa["id"])[0]
print(s)
s_df = fred.get_series_first_release(s)
s_df = s_df.reset_index()
s_df.columns = ["date",s]
print(s_df.shape)

for s in list(df_monthly_nsa["id"])[1:]:
    print(s)
    s_df_ = fred.get_series_first_release(s)
    s_df_ = s_df_.reset_index()
    s_df_.columns = ["date",s]
    s_df = pd.merge(s_df, s_df_)
    print(s_df.shape)

TOTBUSIMNSA
(334, 2)
TOTBUSIRNSA
(334, 3)
TOTBUSMPCIMNSA
(333, 4)
TOTBUSMPCSMNSA
(333, 5)
TOTBUSSMNSA
(333, 6)
IPB50001N
(333, 7)
IPB50002N
(333, 8)
IPB50089N
(333, 9)
IPB51000N
(333, 10)
IPB51100N
(333, 11)
IPB51110N
(333, 12)
IPB51111N
(333, 13)
IPB51112N
(333, 14)
IPB51120N
(333, 15)
IPB51121N
(333, 16)
IPB511221N
(333, 17)
IPB511222N
(333, 18)
IPB51122N
(333, 19)
IPB51123N
(333, 20)
IPB51200N
(333, 21)
IPB51210N
(333, 22)
IPB51211N
(333, 23)
IPB51212N
(333, 24)
IPB51213N
(333, 25)
IPB51214N
(333, 26)
IPB51215N
(333, 27)
IPB51220N
(333, 28)
IPB51222N
(333, 29)
IPB52000N
(333, 30)
IPB52100N
(333, 31)
IPB52110N
(333, 32)
IPB52120N
(333, 33)
IPB52130N
(333, 34)
IPB52131N
(333, 35)
IPB52132N
(333, 36)
IPB52200N
(333, 37)
IPB52300N
(333, 38)
IPB53000N
(333, 39)
IPB53100N
(333, 40)
IPB53110N
(333, 41)
IPB53120N
(333, 42)
IPB53121N
(333, 43)
IPB53122N
(333, 44)
IPB53123N
(333, 45)
IPB53130N
(333, 46)
IPB53131N
(333, 47)
IPB53132N
(333, 48)
IPB53200N
(333, 49)
IPB53210N
(333, 50)
IPB53220N
(333, 51)
IPB53230N
(333, 52)
IPB53240N
(333, 53)
IPB53241N
(333, 54)
IPB53242N
(333, 55)
IPB53300N
(333, 56)
IPB53310N
(333, 57)
IPB53320N
(333, 58)
IPB53810N
(333, 59)
IPB53820N
(333, 60)
IPB54000N
(333, 61)
IPB54100N
(333, 62)
IPB54200N
(333, 63)
IPB54210N
(333, 64)
IPB54220N
(333, 65)
IPB5610CN
(333, 66)
IPB562A3CN
(333, 67)
IPB5640CN
(333, 68)
IPFPNSN
(333, 69)
IPFUELN
(333, 70)
IPG211111CN
(333, 71)
IPG211111N
(333, 72)
IPG211112N
(333, 73)
IPG211N
(333, 74)
IPG21222N
(333, 75)
IPG21223N
(333, 76)
IPG2122N
(333, 77)
IPG2123N
(333, 78)
IPG212N
(333, 79)
IPG213N
(333, 80)
IPG21N
(333, 81)
IPG22111N
(333, 82)
IPG22112N
(333, 83)
IPG2211A2N
(333, 84)
IPG2211N
(333, 85)
IPG2212N
(333, 86)
IPG3111N
(333, 87)
IPG3112N
(333, 88)
IPG3113N
(333, 89)
IPG3114N
(333, 90)
IPG31151N
(333, 91)
IPG3115N
(333, 92)
IPG311611T3N
(333, 93)
IPG3116N
(333, 94)
IPG31192N
(333, 95)
IPG3119N
(333, 96)
IPG311A2N
(333, 97)
IPG311N
(333, 98)
IPG3121N
(333, 99)
IPG3122N
(333, 100)
IPG312N
(333, 101)
IPG3132N
(333, 102)
IPG3133N
(333, 103)
IPG313A4N
(333, 104)
IPG313N
(333, 105)
IPG31411N
(333, 106)
IPG3141N
(333, 107)
IPG3149N
(333, 108)
IPG314N
(333, 109)
IPG315A6N
(333, 110)
IPG315N
(333, 111)
IPG316N
(333, 112)
IPG321219N
(333, 113)
IPG3212A9N
(333, 114)
IPG3212N
(333, 115)
IPG32191N
(333, 116)
IPG32199N
(333, 117)
IPG3219N
(333, 118)
IPG321N
(333, 119)
IPG32212N
(333, 120)
IPG3221N
(333, 121)
IPG32222N
(333, 122)
IPG32223A9N
(333, 123)
IPG3222N
(333, 124)
IPG322N
(333, 125)
IPG323N
(333, 126)
IPG32411N
(333, 127)
IPG32411XN
(333, 128)
IPG324N
(333, 129)
IPG32511A9N
(333, 130)
IPG32512N
(333, 131)
IPG32512T8N
(333, 132)
IPG32513N
(333, 133)
IPG325188AN
(281, 134)
IPG325188N
(281, 135)
IPG325188ZN
(281, 136)
IPG32518N
(281, 137)
IPG3251N
(281, 138)
IPG325212N
(281, 139)
IPG32521N
(281, 140)
IPG3252N
(281, 141)
IPG3253N
(281, 142)
IPG3254N
(281, 143)
IPG32551N
(281, 144)
IPG3255A9N
(281, 145)
IPG3255N
(281, 146)
IPG3255T9N
(281, 147)
IPG3256N
(281, 148)
IPG325N
(281, 149)
IPG3261N
(281, 150)
IPG32621N
(281, 151)
IPG32622A9N
(281, 152)
IPG3262N
(281, 153)
IPG326N
(281, 154)
IPG32711N
(281, 155)
IPG32712N
(281, 156)
IPG3271A4A9N
(281, 157)
IPG3271A9N
(281, 158)
IPG3271N
(281, 159)
IPG3272N
(281, 160)
IPG3273N
(281, 161)
IPG3274N
(281, 162)
IPG3279N
(281, 163)
IPG327N
(281, 164)
IPG3311A2FN
(281, 165)
IPG3311A2N
(281, 166)
IPG3313N
(281, 167)
IPG331411N
(281, 168)
IPG33141N
(281, 169)
IPG3314N
(281, 170)
IPG3315N
(281, 171)
IPG331N
(281, 172)
IPG3325N
(281, 173)
IPG3327N
(281, 174)
IPG332991N
(281, 175)
IPG3329N
(281, 176)
IPG332N
(281, 177)
IPG333111N
(281, 178)
IPG33311N
(281, 179)
IPG33312N
(281, 180)
IPG3331N
(281, 181)
IPG3332N
(281, 182)
IPG3333A9N
(281, 183)
IPG3334N
(281, 184)
IPG3334T6N
(281, 185)
IPG3335N
(281, 186)
IPG3336N
(281, 187)
IPG333N
(281, 188)
IPG3341N
(281, 189)
IPG3342N
(281, 190)
IPG3343N
(281, 191)
IPG33441A1N
(281, 192)
IPG3344N
(281, 193)
IPG3345N
(281, 194)
IPG334N
(281, 195)
IPG3351N
(281, 196)
IPG33521N
(281, 197)
IPG33522N
(281, 198)
IPG3352N
(281, 199)
IPG3353N
(281, 200)
IPG33591N
(281, 201)
IPG33593T9N
(281, 202)
IPG3359N
(281, 203)
IPG335A2N
(281, 204)
IPG335N
(281, 205)
IPG336111BN
(281, 206)
IPG336111N
(281, 207)
IPG336112BN
(281, 208)
IPG336112N
(281, 209)
IPG33611EN
(281, 210)
IPG33611N
(281, 211)
IPG33612N
(281, 212)
IPG3361EN
(281, 213)
IPG3361N
(281, 214)
IPG3361T3N
(281, 215)
IPG336212N
(281, 216)
IPG336214N
(281, 217)
IPG3362N
(281, 218)
IPG3363N
(281, 219)
IPG336411T3N
(281, 220)
IPG3364N
(281, 221)
IPG3364T9N
(281, 222)
IPG3365T9N
(281, 223)
IPG3366N
(281, 224)
IPG336N
(281, 225)
IPG3372A9N
(281, 226)
IPG337N
(281, 227)
IPG339N
(281, 228)
IPG51111N
(281, 229)
IPG51112T9N
(281, 230)
IPG5111N
(281, 231)
IPGMFDN
(281, 232)
IPGMFN
(281, 233)
IPGMFNN
(281, 234)
IPGMFON
(281, 235)
IPHITEK2N
(281, 236)
IPMANSICN
(281, 237)
IPN1133N
(281, 238)
IPN211111GN
(281, 239)
IPN2121N
(281, 240)
IPN21221N
(281, 241)
IPN213111N
(281, 242)
IPN221111N
(281, 243)
IPN221112A9N
(279, 244)
IPN221113N
(279, 245)
IPN22112CN
(279, 246)
IPN22112MN
(279, 247)
IPN22112RN
(279, 248)
IPN2212CN
(279, 249)
IPN2212MN
(279, 250)
IPN2212RN
(279, 251)
IPN2212TN
(279, 252)
IPN311511N
(279, 253)
IPN311512N
(279, 254)
IPN311513N
(279, 255)
IPN311514N
(279, 256)
IPN31152N
(279, 257)
IPN311611T3BN
(279, 258)
IPN311611T3PN
(279, 259)
IPN311611T3ZN
(279, 260)
IPN311615N
(279, 261)
IPN3118N
(279, 262)
IPN31211N
(279, 263)
IPN31212N
(279, 264)
IPN3131N
(279, 265)
IPN3211N
(279, 266)
IPN321211A2N
(279, 267)
IPN32192N
(279, 268)
IPN321991N
(279, 269)
IPN32211N
(279, 270)
IPN322121N
(279, 271)
IPN32213N
(279, 272)
IPN32221N
(279, 273)
IPN32411AN
(279, 274)
IPN32411DN
(279, 275)
IPN32411GN
(279, 276)
IPN32411RN
(279, 277)
IPN32412A9N
(279, 278)
IPN325181N
(279, 279)
IPN325211N
(279, 280)
IPN32522N
(279, 281)
IPN327213N
(279, 282)
IPN32731N
(279, 283)
IPN32732T9N
(279, 284)
IPN3311A2BN
(279, 285)
IPN3311A2CN
(279, 286)
IPN3311A2DN
(279, 287)
IPN3311A2EN
(279, 288)
IPN3311A2PN
(279, 289)
IPN3311A2RN
(279, 290)
IPN3311A2ZN
(279, 291)
IPN331312N
(279, 292)
IPN331314N
(279, 293)
IPN331315A9N
(279, 294)
IPN331316N
(279, 295)
IPN331419N
(278, 296)
IPN3321N
(278, 297)
IPN3322N
(278, 298)
IPN3323N
(278, 299)
IPN3326N
(278, 300)
IPN3328N
(278, 301)
IPN33313N
(278, 302)
IPN33592N
(278, 303)
IPN336213N
(278, 304)
IPN3365N
(278, 305)
IPN3369N
(278, 306)
IPN3371N
(278, 307)
IPN3391N
(278, 308)
IPTB56100N
(278, 309)
IPTB56200N
(278, 310)
IPTB56300N
(278, 311)
IPTB56400N
(278, 312)
IPX005MVN
(278, 313)
IPX4HTK2N
(278, 314)
IPX4HTMVN
(278, 315)
IPX50001N
(278, 316)
IPX5001EN
(278, 317)
IPX50EHVN
(278, 318)
IPX50HTKN
(278, 319)
IPX51HVEN
(278, 320)
IPX52HTVN
(278, 321)
IPX53EHVN
(278, 322)
IPX5410HN
(278, 323)
IPX5421TN
(278, 324)
IPX5EHTKN
(278, 325)
IPX5HTK2N
(278, 326)
IPX5VHT2N
(278, 327)
IPXXX001N
(278, 328)
IPZ53010N
(278, 329)
MVAAUTLTTN
(278, 330)
MVAAUTOASN
(278, 331)
MVAHMTRCKN
(278, 332)
MVALTTRCKN
(278, 333)
MVATOTASSN
(278, 334)
MVATRUCKSN
(278, 335)
MTSDS133FMS
(278, 336)
MTSMFBOM133FMS
(63, 337)
MTSMFBP133FMS
(63, 338)
MTSMFROC133FMS
(63, 339)
MTSO133FMS
(63, 340)
MTSR133FMS
(63, 341)
MVGFD027MNFRBDAL
(63, 342)
MVMTD027MNFRBDAL
(63, 343)
MVPHGFD027MNFRBDAL
(63, 344)
ARIEAPN
(0, 345)
ARIMVPN
(0, 346)
ARINVTN
(0, 347)
MARTSMPCSM44000USN
(0, 348)
MARTSMPCSM441USN
(0, 349)
MARTSMPCSM441XUSN
(0, 350)
MARTSMPCSM442USN
(0, 351)
MARTSMPCSM443USN
(0, 352)
MARTSMPCSM444USN
(0, 353)
MARTSMPCSM4451USN
(0, 354)
MARTSMPCSM445USN
(0, 355)
MARTSMPCSM446USN
(0, 356)
MARTSMPCSM447USN
(0, 357)
MARTSMPCSM448USN
(0, 358)
MARTSMPCSM44W72USN
(0, 359)
MARTSMPCSM44X72USN
(0, 360)
MARTSMPCSM44Y72USN
(0, 361)
MARTSMPCSM44Z72USN
(0, 362)
MARTSMPCSM451USN
(0, 363)
MARTSMPCSM4521EUSN
(0, 364)
MARTSMPCSM452USN
(0, 365)
MARTSMPCSM453USN
(0, 366)
MARTSMPCSM454USN
(0, 367)
MARTSMPCSM722USN
(0, 368)
MARTSSM44W72USN
(0, 369)
MARTSSM44Z72USN
(0, 370)
MRTSIM44000USN
(0, 371)
MRTSIM4400AUSN
(0, 372)
MRTSIM441USN
(0, 373)
MRTSIM4423XUSN
(0, 374)
MRTSIM444USN
(0, 375)
MRTSIM445USN
(0, 376)
MRTSIM448USN
(0, 377)
MRTSIM4521EUSN
(0, 378)
MRTSIM452USN
(0, 379)
MRTSIR44000USN
(0, 380)
MRTSIR4400AUSN
(0, 381)
MRTSIR441USN
(0, 382)
MRTSIR4423XUSN
(0, 383)
MRTSIR444USN
(0, 384)
MRTSIR445USN
(0, 385)
MRTSIR448USN
(0, 386)
MRTSIR4521EUSN
(0, 387)
MRTSIR452USN

(0, 388)
MRTSMPCIM44000USN
(0, 389)
MRTSMPCIM4400AUSN
(0, 390)
MRTSMPCIM441USN
(0, 391)
MRTSMPCIM4423XUSN
(0, 392)
MRTSMPCIM444USN
(0, 393)
MRTSMPCIM445USN
(0, 394)
MRTSMPCIM448USN
(0, 395)
MRTSMPCIM4521EUSN
(0, 396)
MRTSMPCIM452USN
(0, 397)
MRTSMPCSM44000USN
(0, 398)
MRTSMPCSM4400AUSN
(0, 399)
MRTSMPCSM4400CUSN
(0, 400)
MRTSMPCSM44111USN
(0, 401)
MRTSMPCSM44112USN
(0, 402)
MRTSMPCSM4411USN
(0, 403)
MRTSMPCSM4413USN
(0, 404)
MRTSMPCSM441USN
(0, 405)
MRTSMPCSM441XUSN
(0, 406)
MRTSMPCSM4421USN
(0, 407)
MRTSMPCSM44221USN
(0, 408)
MRTSMPCSM442299USN
(0, 409)
MRTSMPCSM4422USN
(0, 410)
MRTSMPCSM4423XUSN
(0, 411)
MRTSMPCSM442USN
(0, 412)
MRTSMPCSM443111USN
(0, 413)
MRTSMPCSM443112USN
(0, 414)
MRTSMPCSM44311USN
(0, 415)
MRTSMPCSM44312USN
(0, 416)
MRTSMPCSM443142USN
(0, 417)
MRTSMPCSM443USN
(0, 418)
MRTSMPCSM44412USN
(0, 419)
MRTSMPCSM44413USN
(0, 420)
MRTSMPCSM4441USN
(0, 421)
MRTSMPCSM444USN
(0, 422)
MRTSMPCSM44511USN
(0, 423)
MRTSMPCSM4451USN
(0, 424)
MRTSMPCSM4453USN
(0, 425)
MRTSMPCSM445USN
(0, 426)
MRTSMPCSM44611USN
(0, 427)
MRTSMPCSM446USN
(0, 428)
MRTSMPCSM447USN
(0, 429)
MRTSMPCSM44811USN
(0, 430)
MRTSMPCSM44812USN
(0, 431)
MRTSMPCSM44814USN
(0, 432)
MRTSMPCSM44819USN
(0, 433)
MRTSMPCSM4481USN
(0, 434)
MRTSMPCSM4482USN
(0, 435)
MRTSMPCSM44831USN
(0, 436)
MRTSMPCSM448USN
(0, 437)
MRTSMPCSM44W72USN
(0, 438)
MRTSMPCSM44X72USN
(0, 439)
MRTSMPCSM44Y72USN
(0, 440)
MRTSMPCSM44Z72USN
(0, 441)
MRTSMPCSM45111USN
(0, 442)
MRTSMPCSM45112USN
(0, 443)
MRTSMPCSM451211USN
(0, 444)
MRTSMPCSM451USN
(0, 445)
MRTSMPCSM452111EUSN
(0, 446)
MRTSMPCSM452111IUSN
(0, 447)
MRTSMPCSM452112EUSN
(0, 448)
MRTSMPCSM452112IUSN
(0, 449)
MRTSMPCSM4521EUSN
(0, 450)
MRTSMPCSM4521IUSN
(0, 451)
MRTSMPCSM45291USN
(0, 452)
MRTSMPCSM45299USN
(0, 453)
MRTSMPCSM4529USN
(0, 454)
MRTSMPCSM452USN
(0, 455)
MRTSMPCSM45321USN
(0, 456)
MRTSMPCSM45322USN
(0, 457)
MRTSMPCSM4532USN
(0, 458)
MRTSMPCSM45330USN
(0, 459)
MRTSMPCSM453USN
(0, 460)
MRTSMPCSM4541USN
(0, 461)
MRTSMPCSM45431USN
(0, 462)
MRTSMPCSM454USN
(0, 463)
MRTSMPCSM7221USN
(0, 464)
MRTSMPCSM7222USN
(0, 465)
MRTSMPCSM7224USN
(0, 466)
MRTSMPCSM7225USN
(0, 467)
MRTSMPCSM722USN
(0, 468)
MRTSSM44000USN
(0, 469)
MRTSSM4400AUSN
(0, 470)
MRTSSM4400CUSN
(0, 471)
MRTSSM44111USN
(0, 472)
MRTSSM44112USN
(0, 473)
MRTSSM4411USN
(0, 474)
MRTSSM4413USN
(0, 475)
MRTSSM441USN
(0, 476)
MRTSSM441XUSN
(0, 477)
MRTSSM4421USN
(0, 478)
MRTSSM44221USN
(0, 479)
MRTSSM442299USN
(0, 480)
MRTSSM4422USN
(0, 481)
MRTSSM4423XUSN
(0, 482)
MRTSSM442USN
(0, 483)
MRTSSM443111USN
(0, 484)
MRTSSM443112USN
(0, 485)
MRTSSM44311USN
(0, 486)
MRTSSM44312USN
(0, 487)
MRTSSM443142USN
(0, 488)
MRTSSM443USN
(0, 489)
MRTSSM44412USN
(0, 490)
MRTSSM44413USN
(0, 491)
MRTSSM4441USN
(0, 492)
MRTSSM444USN
(0, 493)
MRTSSM44511USN
(0, 494)
MRTSSM4451USN
(0, 495)
MRTSSM4453USN
(0, 496)
MRTSSM445USN
(0, 497)
MRTSSM44611USN
(0, 498)
MRTSSM446USN
(0, 499)
MRTSSM447USN
(0, 500)
MRTSSM44811USN
(0, 501)
MRTSSM44812USN
(0, 502)
MRTSSM44814USN
(0, 503)
MRTSSM44819USN
(0, 504)
MRTSSM4481USN
(0, 505)
MRTSSM4482USN
(0, 506)
MRTSSM44831USN
(0, 507)
MRTSSM448USN
(0, 508)
MRTSSM44W72USN
(0, 509)
MRTSSM44X72USN
(0, 510)
MRTSSM44Y72USN
(0, 511)
MRTSSM44Z72USN
(0, 512)
MRTSSM45111USN
(0, 513)
MRTSSM45112USN
(0, 514)
MRTSSM451211USN
(0, 515)
MRTSSM451USN
(0, 516)
MRTSSM452111EUSN
(0, 517)
MRTSSM452111IUSN
(0, 518)
MRTSSM452112EUSN
(0, 519)
MRTSSM452112IUSN
(0, 520)
MRTSSM4521EUSN
(0, 521)
MRTSSM4521IUSN
(0, 522)
MRTSSM45291USN
(0, 523)
MRTSSM45299USN
(0, 524)
MRTSSM4529USN
(0, 525)
MRTSSM452USN
(0, 526)
MRTSSM45321USN
(0, 527)
MRTSSM45322USN
(0, 528)
MRTSSM4532USN
(0, 529)
MRTSSM45330USN
(0, 530)
MRTSSM453USN
(0, 531)
MRTSSM4541USN
(0, 532)
MRTSSM45431USN
(0, 533)
MRTSSM454USN
(0, 534)
MRTSSM7221USN
(0, 535)
MRTSSM7222USN
(0, 536)
MRTSSM7224USN
(0, 537)
MRTSSM7225USN
(0, 538)
MRTSSM722USN
(0, 539)
RETAILIMNSA
(0, 540)
RETAILIRNSA
(0, 541)
RETAILMPCIMNSA
(0, 542)
RETAILMPCSMNSA
(0, 543)
RETAILNS
(0, 544)
RETAILSMNSA
(0, 545)
RSAFSNA
(0, 546)
RSAOMVN
(0, 547)
RSBMGESDN
(0, 548)
RSCCASN
(0, 549)
RSDBSN
(0, 550)
RSDSELDN
(0, 551)
RSEASN
(0, 552)
RSFHFSN
(0, 553)
RSFSDPN
(0, 554)
RSFSXMVN

KeyboardInterrupt:

In [99]:
print(s_df.shape)
s_df.head()

(333, 11)

,date,ISRATIO,TOTBUSIMNSA,TOTBUSIRNSA,TOTBUSMPCIMNSA,TOTBUSMPCIMSA,TOTBUSMPCSMNSA,TOTBUSMPCSMSA,TOTBUSSMNSA,TOTBUSSMSA,CAPB00004S
0,1992-02-01,1.5,809329,1.63,0.8,0.2,3.7,0.5,496844,520472,74.1241
1,1992-03-01,1.49,813301,1.5,0.5,0.4,9.3,2,542833,530763,74.2823
2,1992-04-01,1.48,819247,1.53,0.7,0.4,-1.7,0.5,533768,533430,74.4538
3,1992-05-01,1.49,815688,1.52,-0.4,-0.1,0.7,0.6,537400,536869,74.6388
4,1992-06-01,1.47,812610,1.44,-0.4,0.6,5.2,0.9,565572,541624,74.8358

In [102]:
sp500 = fred.get_series("SP500")
sp500 = sp500.reset_index()
sp500.columns = ['date', 'sp500']
print(sp500.shape)
sp500.head()

(2608, 2)

        date    sp500
0 2010-01-01      NaN
1 2010-01-04  1132.99
2 2010-01-05  1136.52
3 2010-01-06  1137.14
4 2010-01-07  1141.69

In [103]:
x = pd.merge(s_df, sp500)
print(x.shape)
x.head()

(85, 12)

,date,ISRATIO,TOTBUSIMNSA,TOTBUSIRNSA,TOTBUSMPCIMNSA,TOTBUSMPCIMSA,TOTBUSMPCSMNSA,TOTBUSMPCSMSA,TOTBUSSMNSA,TOTBUSSMSA,CAPB00004S,sp500
0,2010-01-01,1.25,1.32077e+06,1.4,0.8,0.1,-13.1,0.6,941736,1.03321e+06,124.009,NaN
1,2010-02-01,1.27,1.33512e+06,1.42,1.1,0.6,-0.3,0.3,938975,1.03659e+06,123.785,1089.19
2,2010-03-01,1.23,1.34539e+06,1.21,0.8,0.6,18.2,1.9,1.1102e+06,1.05678e+06,123.561,1115.71
3,2010-04-01,1.23,1.35234e+06,1.25,0.5,0.4,-2.8,1.1,1.07966e+06,1.06831e+06,123.339,1178.10
4,2010-06-01,1.26,1.35036e+06,1.22,0.2,0.8,3.1,-0.1,1.10973e+06,1.06323e+06,122.906,1070.71

In [105]:
x['sp500_lead1'] = x['sp500'].shift(-1)
x.head()

,date,ISRATIO,TOTBUSIMNSA,TOTBUSIRNSA,TOTBUSMPCIMNSA,TOTBUSMPCIMSA,TOTBUSMPCSMNSA,TOTBUSMPCSMSA,TOTBUSSMNSA,TOTBUSSMSA,CAPB00004S,sp500,sp500_lead1
0,2010-01-01,1.25,1.32077e+06,1.4,0.8,0.1,-13.1,0.6,941736,1.03321e+06,124.009,NaN,1089.19
1,2010-02-01,1.27,1.33512e+06,1.42,1.1,0.6,-0.3,0.3,938975,1.03659e+06,123.785,1089.19,1115.71
2,2010-03-01,1.23,1.34539e+06,1.21,0.8,0.6,18.2,1.9,1.1102e+06,1.05678e+06,123.561,1115.71,1178.10
3,2010-04-01,1.23,1.35234e+06,1.25,0.5,0.4,-2.8,1.1,1.07966e+06,1.06831e+06,123.339,1178.10,1070.71
4,2010-06-01,1.26,1.35036e+06,1.22,0.2,0.8,3.1,-0.1,1.10973e+06,1.06323e+06,122.906,1070.71,1027.37

In [106]:
x.to_csv("../data/monthly_sp500_modeling.csv", index=False)